### ISSUE TITLE
video from peer is not streaming

### ISSUE THREAD

**Issue by seetharaghavan** [pj035/angular2-webrtc-video-example#1]
Hi I have tried your code in angular. I have connected them to sockets. The offer and answer procedure works fine. I get the media stream from remote as well but the remote content is not streaming. The video goes blank with the loader. Could you help me out of this

**Comment by pj035** [comment]
@seetharaghavan sorry for the late response. I was very inactive on this platform. The code we find in this repository is really outdated and a lot of the dependencies were in some beta / WIP back then. 

Anyways, I've looked into the details. The problem is that my code relies on `url.createObjectUrl` to create and attach the video stream [on this line](https://github.com/pj035/angular2-webrtc-video-example/blob/99e311b0e5513fd05f2f4436d433d266b9965653/frontend/src/app/webrtc-chat/webrtc-chat.component.ts#L31). This feature is not supported anymore by modern browsers as you read [here on MDN](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL#Using_object_URLs_for_media_streams). Instead you have to set the video element's `srcObject` directly to the `MediaStream` object, that is part of each `WebRTCClient`.

A quick workaround (without cleaning up anything) would be to alter the [line 7 here](https://github.com/pj035/angular2-webrtc-video-example/blob/99e311b0e5513fd05f2f4436d433d266b9965653/frontend/src/app/webrtc-chat/webrtc-chat.component.html#L7) to `<video controls autoplay width="320" height="240" [srcObject]="client.stream">` and comment out its child element (`source`).
